//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusBookingSystem_.BBS_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusInformation
    {
        public int Id { get; set; }
        public string BusName { get; set; }
        public System.DateTime DepartTime { get; set; }
        public System.DateTime ArrivalTime { get; set; }
        public int Rows { get; set; }
        public int Columns { get; set; }
        public decimal Price { get; set; }
        public string Stops { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string CompanyName { get; set; }
    }
}
